### ISSUE TITLE
Event delegation should skip "disabled" elements

### ISSUE THREAD

**Issue by mairatma** [mairatma/metal-events#2]
Events don't trigger for **disabled** elements natively, even when bubbling. Our event delegation doesn't respect that though, since it catches the event in the component's element and doesn't check for disabled states.

Need to investigate which elements are automatically skipped natively (button for sure, but maybe more of them too).

**Comment by fernandosouza** [comment]
Some links which can be helpful.

https://w3c.github.io/html/disabled-elements.html#disabled-elements
https://html.spec.whatwg.org/#concept-fe-disabled

According to the specs:
"A form control that is disabled must prevent any click events that are queued on the user interaction task source from being dispatched on the element."

I hope it can help.

**Comment by mairatma** [comment]
Nice, so this should probably happen for any form element right? It'd be good to make sure of that by testing it out a bit.

This shouldn't be hard to fix by the way, probably just a check on our delegation code. If you have some time and want to grab this, feel free to do it @fernandosouza :D

**Comment by fernandosouza** [comment]
Ok, @mairatma. I think there is a relation to the metal-select disable attribute.

**Comment by mairatma** [comment]
You're right, that's even better then :)

**Comment by mairatma** [comment]
This has been moved to https://github.com/metal/metal/issues/2. @fernandosouza, as soon as you accept the invitation I can assign this to you there :)
